### PR TITLE
Add ANT Rinkeby deployment to README

### PR DESCRIPTION
**Pull request by bingen**

### CODE REVIEW

**Comment by AquiGorka** [comment]
👍 to having an "oficial" `ANT` for testing. The facuet idea sounds interesting.

I remember asking for test `ANT` when I was developing DIrua, back then @izqui sent over another address:

image

**Comment by bingen** [comment]
Absolutely, the idea of the faucet would be cool. But would we restrict it somehow?

**Comment by izqui** [comment]
We could only mint a fixed amount of tokens per tx, doubt anyone will be motivated enough to mint fake ANT

**Comment by sohkai** [comment]
Going to close this for now—we can re-create this when we deploy the new controller mechanism.

**Pull request closed without merging**
